name: CI/CD Pipeline

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

 - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ngweijiang/app:${{ github.sha }} .
        docker tag ngweijiang/app:${{ github.sha }} ngweijiang/app:latest

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ngweijiang/app:${{ github.sha }}
        docker push ngweijiang/app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/app app=your-dockerhub-user/app:${{ github.sha }}
