name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Triggers the workflow when code is pushed to the master branch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04  # 明确指定运行环境
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # This step checks out the repository code

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ngweijiang/app:${{ github.sha }} .
          docker tag ngweijiang/app:${{ github.sha }} ngweijiang/app:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ngweijiang/app:${{ github.sha }}
          docker push ngweijiang/app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push_to_registry  # Correctly reference the 'push_to_registry' job
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app app=ngweijiang/app:${{ github.sha }}
