name: CI/CD Pipeline

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t ngweijiang/app:${{ github.sha }} .
        docker login -u ngweijiang -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ngweijiang/app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/app app=your-dockerhub-user/app:${{ github.sha }}
