name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ngweijiang/app:${{ github.sha }} .
          docker tag ngweijiang/app:${{ github.sha }} ngweijiang/app:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ngweijiang/app:${{ github.sha }}
          docker push ngweijiang/app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup kubeconfig
        run: |
    mkdir -p ~/.kube  # 创建目录
    echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config  # 写入配置
    kubectl config set-context --current --namespace=${{ secrets.K8S_NAMESPACE }}

    - name: Debug kubeconfig
      run: |
    ls -l ~/.kube
    cat ~/.kube/config

      - name: Verify Kubernetes cluster connection
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app app=ngweijiang/app:${{ github.sha }}
