name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 构建并标记 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ngweijiang/app:${{ github.sha }} .
          docker tag ngweijiang/app:${{ github.sha }} ngweijiang/app:latest

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ngweijiang/app:${{ github.sha }}
          docker push ngweijiang/app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2

      # 设置 kubeconfig 文件
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config
          export KUBECONFIG=~/.kube/config
          echo "Kubeconfig file content:"
          kubectl config view

      # 列出上下文信息以调试
      - name: List contexts
        run: |
          kubectl config get-contexts
          kubectl config current-context

      # 验证 Kubernetes 集群连接
      - name: Verify Kubernetes cluster connection
        run: kubectl cluster-info

      # 部署应用到 Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app app=ngweijiang/app:${{ github.sha }}
